# Generated by Django 5.2.9 on 2026-01-21 17:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название конференции')),
                ('short_title', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-префикс')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('start_date', models.DateField(verbose_name='Дата начала конференции')),
                ('registration_deadline', models.DateTimeField(verbose_name='Дедлайн регистрации/подачи')),
                ('notification_date', models.DateField(verbose_name='Дата оглашения результатов')),
                ('program', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Программа конференции')),
                ('committee', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Оргкомитет')),
                ('poster', models.ImageField(upload_to='conf/posters/', verbose_name='Постер (широкоугольный)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='conf/gallery/', verbose_name='Файл (Фото или Видео)')),
                ('is_video', models.BooleanField(default=False, verbose_name='Это видео?')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'Медиа галереи',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название работы')),
                ('authors_list', models.TextField(blank=True, help_text='ФИО, ученая степень, организация (каждый соавтор с новой строки или через запятую)', verbose_name='Список соавторов')),
                ('abstract_text', models.TextField(blank=True, help_text='Краткое описание работы (200-500 слов)', verbose_name='Аннотация')),
                ('keywords', models.CharField(blank=True, help_text='Введите 3-5 слов через запятую', max_length=255, verbose_name='Ключевые слова')),
                ('status', models.CharField(choices=[('under_review', 'На проверке'), ('revision', 'Требуется доработка'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='under_review', max_length=20, verbose_name='Статус')),
                ('admin_remark', models.TextField(blank=True, help_text="Опишите, что именно нужно исправить, если статус 'Доработка'", verbose_name='Замечания администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='conferences.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'unique_together': {('user', 'conference')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Файл версии')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('author_comment', models.TextField(blank=True, help_text='Что изменилось в этой версии?', verbose_name='Комментарий автора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='conferences.submission')),
            ],
            options={
                'verbose_name': 'Версия работы',
                'verbose_name_plural': 'Версии работы',
                'ordering': ['-created_at'],
            },
        ),
    ]
