# Generated by Django 5.2.9 on 2026-01-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='admin_remark',
        ),
        migrations.AddField(
            model_name='submissionversion',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Замечания к этой конкретной версии', verbose_name='Ответ оргкомитета'),
        ),
    ]
