# Generated by Django 5.2.9 on 2026-01-25 04:23

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_remove_submission_admin_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='participation_fee',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Плата за участие'),
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_format',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Формат работы'),
        ),
        migrations.AddField(
            model_name='conference',
            name='venue',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Место проведения (подробно)'),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('chair', 'Председатель'), ('vice_chair', 'Зам. председателя'), ('member', 'Член комитета'), ('secretary', 'Секретарь')], default='member', max_length=20, verbose_name='Роль')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('organization', models.CharField(blank=True, max_length=500, verbose_name='Организация')),
                ('photo', models.ImageField(blank=True, upload_to='conf/committee/', verbose_name='Фотография')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'Член комитета',
                'verbose_name_plural': 'Члены комитета',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, upload_to='conf/contacts/', verbose_name='Фотография')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='conf/documents/', verbose_name='Файл документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
