# Generated by Django 6.0.1 on 2026-02-03 07:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conference_participation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='conference',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='conference',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='conference',
            name='location_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Место проведения (подробно)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='conference',
            name='location_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='conference',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='conference',
            name='participation_fee_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Плата за участие'),
        ),
        migrations.AddField(
            model_name='conference',
            name='participation_fee_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Плата за участие'),
        ),
        migrations.AddField(
            model_name='conference',
            name='participation_fee_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Плата за участие'),
        ),
        migrations.AddField(
            model_name='conference',
            name='short_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='conference',
            name='short_title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='conference',
            name='short_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_format_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Формат работы'),
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_format_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Формат работы'),
        ),
        migrations.AddField(
            model_name='conference',
            name='submission_format_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Формат работы'),
        ),
        migrations.AddField(
            model_name='conference',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Название конференции'),
        ),
        migrations.AddField(
            model_name='conference',
            name='title_kk',
            field=models.CharField(max_length=500, null=True, verbose_name='Название конференции'),
        ),
        migrations.AddField(
            model_name='conference',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Название конференции'),
        ),
    ]
