# Generated by Django 6.0.1 on 2026-02-03 07:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_conference_description_en_conference_description_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='location_description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Место проведения (подробно)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='location_description_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Место проведения (подробно)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='location_description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Место проведения (подробно)'),
        ),
    ]
