# Generated by Django 6.0.1 on 2026-02-03 08:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_conference_location_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='venue',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='bio_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='organization_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='organization_kk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='organization_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='position_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='position_kk',
            field=models.CharField(max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='position_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='conference',
            name='committee_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Общее описание комитета, если нужно', null=True, verbose_name='Оргкомитет (текст)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='committee_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Общее описание комитета, если нужно', null=True, verbose_name='Оргкомитет (текст)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='committee_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Общее описание комитета, если нужно', null=True, verbose_name='Оргкомитет (текст)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='program_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Программа конференции'),
        ),
        migrations.AddField(
            model_name='conference',
            name='program_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Программа конференции'),
        ),
        migrations.AddField(
            model_name='conference',
            name='program_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Программа конференции'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='position_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='caption_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='committee',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Общее описание комитета, если нужно', verbose_name='Оргкомитет (текст)'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description_kk',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место проведения (коротко)'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='location_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения (коротко)'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='location_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения (коротко)'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='location_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Место проведения (коротко)'),
        ),
        migrations.AlterField(
            model_name='submissionversion',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Ответ оргкомитета'),
        ),
        migrations.AlterField(
            model_name='submissionversion',
            name='author_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий автора'),
        ),
    ]
