# Generated by Django 5.2.11 on 2026-02-16 15:17

import conferences.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_remove_conference_venue_committeemember_bio_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_file',
            field=models.FileField(blank=True, null=True, upload_to=conferences.models.get_conference_pdf_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Финальный файл (PDF)'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Автор (Участник)'), ('organizer', 'Организатор (Админ/Редактор)')], default='author', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('under_review', 'На проверке'), ('revision', 'Требуется доработка'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('ready_for_print', 'Готово к печати (верстка)')], default='under_review', max_length=20, verbose_name='Статус'),
        ),
    ]
