# Generated by Django 5.2.11 on 2026-02-17 08:22

import conferences.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_submission_final_file_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'verbose_name': 'Kонференция', 'verbose_name_plural': 'Kонференции'},
        ),
        migrations.AlterField(
            model_name='submissionversion',
            name='file',
            field=models.FileField(upload_to=conferences.models.get_submission_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='Файл версии (DOC/DOCX)'),
        ),
    ]
