# Generated by Django 5.2.11 on 2026-02-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_alter_conference_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceedings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='conf/proceedings/', verbose_name='Файл сборника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings_archive', to='conferences.conference')),
            ],
            options={
                'verbose_name': 'Сборник трудов',
                'verbose_name_plural': 'Сборники трудов',
                'ordering': ['-created_at'],
            },
        ),
    ]
