# Generated by Django 5.2.11 on 2026-02-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_proceedings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedings',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings_archive', to='conferences.conference', unique=True),
        ),
    ]
